CREATE TABLE [dbo].[orderupdated_order] (

	[order_bk] varchar(8000) NULL, 
	[orderNumber] varchar(8000) NULL, 
	[status_value] varchar(8000) NULL, 
	[orderDate] varchar(8000) NULL, 
	[salesBrand] varchar(8000) NULL, 
	[country] varchar(8000) NULL, 
	[total_creditedAmount] float NULL, 
	[EventEnqueuedUtcTime] datetime2(6) NULL, 
	[updated_datetime] datetime2(6) NULL, 
	[invoiceAddress_address_countryCode] varchar(8000) NULL, 
	[total_handlingFee] float NULL, 
	[total_shippingFee] float NULL, 
	[total_salesAmount] float NULL, 
	[total_discount] float NULL, 
	[total_totalAmount] float NULL, 
	[invoiceAddress_lastName] varchar(8000) NULL, 
	[invoiceAddress_email] varchar(8000) NULL, 
	[invoiceAddress_mobilePhone] varchar(8000) NULL, 
	[invoiceAddress_address_street] varchar(8000) NULL, 
	[invoiceAddress_address_postalCode] varchar(8000) NULL, 
	[invoiceAddress_address_city] varchar(8000) NULL, 
	[fraudStatus_value] varchar(8000) NULL, 
	[fraudStatus_title] varchar(8000) NULL, 
	[deliveryStatus_value] varchar(8000) NULL, 
	[deliveryStatus_title] varchar(8000) NULL, 
	[customerNumber] varchar(8000) NULL, 
	[invoiceAddress_firstName] varchar(8000) NULL, 
	[currency] varchar(8000) NULL, 
	[source_name] varchar(8000) NULL, 
	[source_title] varchar(8000) NULL, 
	[source_isExternal] bit NULL, 
	[clientIP] varchar(8000) NULL, 
	[status_title] varchar(8000) NULL, 
	[rn] bigint NULL
);